apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-dynamic
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/magal-devops/gitops-monorepo.git
        revision: main
        directories:
        - path: "applications/*/*"
  template:
    metadata:
      name: "{{index .path.segments 1}}-{{index .path.segments 2}}"
      labels:
        project: "{{index .path.segments 1}}"
        environment: "{{index .path.segments 2}}"
        name: "{{index .path.segments 1}}"
        team: magal-devops
        managed-by: argocd-applicationset
    spec:
      project: default
      source:
        path: "applications/{{index .path.segments 1}}/{{index .path.segments 2}}"
        repoURL: https://github.com/magal-devops/gitops-monorepo.git
        targetRevision: HEAD
        plugin:
          name: argocd-merge-helm-values
          env:
            - name: NAMESPACE
              value: "{{index .path.segments 1}}-{{index .path.segments 2}}"
            - name: HELM_RELEASE_NAME
              value: "{{index .path.segments 1}}-{{index .path.segments 2}}2"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{index .path.segments 1}}-{{index .path.segments 2}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
      revisionHistoryLimit: 5