apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-merge-helm-values
    spec:
      init:
        command: [sh, -c]
        args:
        - |
          export HELM_CACHE_HOME=/tmp/.helm
          export HELM_CONFIG_HOME=/tmp/.helm
          export HELM_DATA_HOME=/tmp/.helm
          
          GITHUB_TOKEN=$(cat /etc/github-credentials/token)
          GITHUB_USERNAME=$(cat /etc/github-credentials/username)
          echo "${GITHUB_TOKEN}" | helm registry login ghcr.io --username ${GITHUB_USERNAME} --password-stdin
      generate:
        command: [sh, -c]
        args:
        - |
          export HELM_CACHE_HOME=/tmp/.helm
          export HELM_CONFIG_HOME=/tmp/.helm
          export HELM_DATA_HOME=/tmp/.helm
          
          VALUE_ARGS=""
          for f in *.yaml; do
            [ -f "$f" ] || continue 
            VALUE_ARGS="$VALUE_ARGS -f $f"
          done

          helm template ${ARGOCD_ENV_HELM_CHART_REPO}/${ARGOCD_ENV_HELM_CHART_NAME} \
          --version ${ARGOCD_ENV_HELM_CHART_VERSION} \
          --namespace ${ARGOCD_ENV_NAMESPACE} \
          $VALUE_ARGS
