apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: argocd
type: Opaque
data:
  # Substitua 'YOUR_GITHUB_TOKEN_BASE64' pelo seu token GitHub em base64
  # Para gerar: echo -n 'seu_token_aqui' | base64
  token: YOUR_GITHUB_TOKEN_BASE64 
  username: YOUR_GITHUB_USERNAME